export default {
  plugins: ["prettier-plugin-tailwindcss"],
  tailwindFunctions: ["cva", "cn"],
  tailwindStylesheet: "src/app/styles/global.css",
  arrowParens: "always",
  bracketSpacing: true,
  endOfLine: "lf",
  htmlWhitespaceSensitivity: "ignore",
  singleAttributePerLine: false,
  bracketSameLine: false,
  jsxSingleQuote: false,
  printWidth: 80,
  proseWrap: "preserve",
  quoteProps: "as-needed",
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "all",
  useTabs: false,
  embeddedLanguageFormatting: "auto",
  experimentalTernaries: false,
};
