name: Auto merge

on:
  pull_request

jobs:
  merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.DEPEND_MERGE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge PR
        run: gh pr merge "${{ github.head_ref }}" --merge --auto
        env:
          GH_TOKEN: ${{ secrets.DEPEND_MERGE }}
